// <auto-generated />
namespace Pottrcko.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedImageURLClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedImageURLClient));
        
        string IMigrationMetadata.Id
        {
            get { return "202109231101400_AddedImageURLClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
